changelog:
  exclude:
    labels:
      - dependencies
      - internal
  categories:
    - title: Improvements
      labels:
        - "*"
      exclude:
        labels:
          - bug
    - title: Bug fixes
      labels:
        - bug
